NAME_DISPLAY_MAP: dict = {
    "vt_symbol": "VT symbol",
    "direction": "Direction",
    "price": "Price",
    "volume": "Volume",
    "time": "Execution time (seconds)",
    "interval": "Interval (seconds)",
    "offset": "Offset",
    "status": "Algo status",
    "traded_price": "Traded price",
    "traded": "Traded volume",
    "left": "Remaining quantity",
    "order_volume": "Order volume",
    "timer_count": "Timer count",
    "total_count": "Total count",
    "template_name": "Template name",
    "display_volume": "Display volume",
    "price_add": "Price add",
    "step_price": "Price step",
    "step_volume": "Volume step",
    "order_type": "Order type",
    "active_vt_symbol": "Active VT symbol",
    "passive_vt_symbol": "Passive VT symbol",
    "spread_up": "Spread up",
    "spread_down": "Spread down",
    "max_pos": "Max position",
    "start_time": "Start time",
    "end_time": "End time",
    "min_volume": "Min volume",
    "max_volume": "Max volume",
    "volume_change": "Volume change",
}
